In [4]:
#import packages and read in the .dat files in a dataframe
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns

#read in the .dat files
df = pd.read_csv('output.csv', sep=',')
df

,date_time,device_id,tmp,hum,CO2,VOC,vis,IR,WIFI,BLE,rssi,channel_rssi,snr,gateway,channel_index,spreading_factor,bandwidth,f_cnt
0,2022-10-10 14:09:26,hka-aqm-a014,21.10,55.26,528,450,488,61,2,3,-63,-63,8.2,drag-lps8-01,1,7,125000,2
1,2022-10-10 14:18:26,hka-aqm-a014,22.37,51.95,526,450,528,72,2,2,-55,-55,8.2,drag-lps8-01,4,7,125000,3
2,2022-10-10 14:18:47,hka-aqm-a014,22.44,51.73,525,450,647,102,2,1,-57,-57,6.8,drag-lps8-01,5,7,125000,4
3,2022-10-10 14:19:07,hka-aqm-a014,22.50,51.63,525,450,766,130,2,1,-55,-55,8.5,drag-lps8-01,6,7,125000,5
4,2022-10-10 14:19:26,hka-aqm-a014,22.56,51.41,526,450,877,157,1,1,-59,-59,8.5,drag-lps8-01,7,7,125000,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824353,2023-09-26 22:50:49,hka-aqm-am308,27.38,37.58,520,950,7,3,2,0,-73,-73,12.2,drag-lps8-05,4,8,125000,12637
824354,2023-09-26 23:05:56,hka-aqm-am308,27.36,37.58,529,948,4,2,1,0,-72,-72,10.0,drag-lps8-05,6,8,125000,12638
824355,2023-09-26 23:21:03,hka-aqm-am308,27.35,37.61,529,966,4,0,6,27,-75,-75,11.8,drag-lps8-05,0,8,125000,12639
824356,2023-09-26 23:36:09,hka-aqm-am308,27.34,37.65,525,944,4,0,0,0,-75,-75,12.0,drag-lps8-05,3,8,125000,12640
824357,2023-09-26 23:51:16,hka-aqm-am308,27.33,37.65,525,951,4,0,0,0,-70,-70,8.2,drag-lps8-05,5,8,125000,12641

In [9]:
import pandas as pd
import glob

# Initialize an empty DataFrame
df = pd.DataFrame()

# Get a list of all .dat files in the directory
files = glob.glob('data\hka-aqm-a\*.dat')

# Loop through the list of files
for file in files:
    # Read each file into a DataFrame
    df_temp = pd.read_csv(file, sep=';', skiprows=1, skipinitialspace=True)
    
    # Append the data from the current file to the main DataFrame
    df = pd.concat([df, df_temp], ignore_index=True)

In [12]:
df.device_id.nunique()

36

In [2]:
df = pd.

NameError: name 'df' is not defined

In [11]:
df.to_csv('output.csv', index=False)

In [5]:
#na in df
df.isna().sum()

date_time              0
device_id              0
tmp                    0
hum                    0
CO2                    0
VOC                    0
vis                    0
IR                     0
WIFI                   0
BLE                    0
rssi                   0
channel_rssi           0
snr                 5862
gateway                0
channel_index          0
spreading_factor       0
bandwidth              0
f_cnt                  0
dtype: int64

In [31]:
df.dtypes

date_time            object
device_id            object
tmp                 float64
hum                 float64
CO2                   int64
VOC                   int64
vis                   int64
IR                    int64
WIFI                  int64
BLE                   int64
rssi                  int64
channel_rssi          int64
snr                 float64
gateway              object
channel_index         int64
spreading_factor      int64
bandwidth             int64
f_cnt                 int64
dtype: object

In [33]:
df['date_time'] = pd.to_datetime(df['date_time'])

In [27]:
#df where column 12 is na
df[df["snr"].isna()]

,date_time,device_id,tmp,hum,CO2,VOC,vis,IR,WIFI,BLE,rssi,channel_rssi,snr,gateway,channel_index,spreading_factor,bandwidth,f_cnt
1065,2023-01-20 16:07:57,hka-aqm-li001,18.96,37.65,1065,1009,49,9,5,66,-118,-118,NaN,drag-outd-01,4,7,125000,754
1071,2023-01-20 17:39:36,hka-aqm-li001,19.10,36.42,897,880,46,7,5,66,-118,-118,NaN,drag-outd-01,4,7,125000,761
1078,2023-01-20 19:40:56,hka-aqm-li001,19.04,36.12,771,782,25,4,5,66,-116,-116,NaN,drag-outd-01,4,7,125000,770
1093,2023-01-20 23:43:42,hka-aqm-li001,18.49,36.45,618,664,10,1,5,66,-116,-116,NaN,drag-outd-01,6,7,125000,789
1098,2023-01-21 00:59:16,hka-aqm-li001,18.43,36.55,590,649,10,1,5,66,-116,-116,NaN,drag-outd-01,6,7,125000,794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
373089,2023-09-25 11:15:07,hka-aqm-li149,20.83,51.92,762,1591,353,124,0,9,-118,-118,NaN,drag-lps8-01,0,7,125000,5934
373111,2023-09-25 15:49:58,hka-aqm-li149,25.22,39.13,616,1005,1488,516,0,0,-112,-112,NaN,drag-lps8-08,1,7,125000,5956
373130,2023-09-25 17:58:45,hka-aqm-li149,25.54,38.31,514,870,710,260,0,1,-109,-109,NaN,drag-lps8-02,5,7,125000,5976
373193,2023-09-26 08:43:45,hka-aqm-li149,20.05,49.38,534,873,289,82,2,2,-112,-112,NaN,drag-lps8-02,7,7,125000,6039
373238,2023-09-26 20:04:58,hka-aqm-li149,25.66,47.04,495,1590,7,1,1,1,-115,-115,NaN,drag-lps8-01,2,7,125000,6086

In [ ]:
#data visualization
#plotting the data with plotly.express
import plotly.express as px
fig = px.line(df.sort_values("date_time"), x='date_time', y='snr', title='SNR over time')
fig.show()

In [ ]:
#plot CO2 over time
fig = px.line(df.sort_values("date_time"), x='date_time', y='CO2', title='CO2 over time')
fig.show()